# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

#####################
# Site configs
title: Material Doc
owner:
  name: Tankery Chen
  link: http://tankery.me
  email: tankery.chen@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  A Material Designed Jekyll template for documentation site. Using structure
  from Jekyll Documentation, and style from Materialize.
baseurl: "/material-doc" # the subpath of your site, e.g. /blog

# Specific social links, now we support following social account:
# github, twitter, weibo, google-plus, instagram, facebook, stack-overflow
# To support more social links, edit url in _data/socials.yml
# Remenber, always use a name that support by Font Awesome, to make sure the
# icon is shown.
socials:
  - name: github
    user: tankery
  - name: stack-overflow
    user: 1038900

#####################
# Site styles
palette:
  primary: "#5c6bc0" # indigo, lighten-1
  secondary: "#7986cb" # indigo lighten-2
  tertiary: "#9fa8da" # indigo lighten-3
  colored_text: "#c5cae9" # indigo lighten-4
  highlight: "#f44336" # red

#####################
# Build settings
collections:
  docs:
    output: true

markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge

sass:
  #style: compressed
